# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]

#     steps:
#     - uses: actions/checkout@v4

#     - name: Debug Directory Structure
#       run: |
#         pwd
#         ls -la
#         ls -la week14_cicd

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'

#     - name: Install Dependencies
#       working-directory: ./week14_cicd
#       run: npm ci

#     - name: Build Project
#       working-directory: ./week14_cicd
#       run: npm run build --if-present

#     - name: Run Tests
#       working-directory: ./week14_cicd
#       run: npm test
